//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URL_Shorten_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class url
    {
        public int ID { get; set; }
        public string short_url { get; set; }
        public string real_url { get; set; }
    }
}
